version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.2.1
  aws-ecs: circleci/aws-ecs@3.2.0
  python:  circleci/python@2.1.1

jobs:
  aws-ecr:
    docker:
      - image: cimg/python:3.11.0
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest
      - setup_remote_docker:
          version: 20.10.11
      - aws-ecr/build-and-push-image:
          public-registry: true
          dockerfile: Dockerfile
          repo: aws
          tag: latest,$CIRCLE_SHA1
    
      - aws-ecs/deploy-service-update: # orb built-in job
          requires:
            - aws-ecr/build-and-push-image
          family: 'ecs-service-3'
          cluster: 'aws-cluster-3'
          container-image-name-updates: 'container=ecs-service-3,tag=${CIRCLE_SHA1}'

workflows:
# indivudual work lines
  build-and-push-to-ecr:
    jobs:
      - aws-ecr:
      # context r for variables
          context:
            - AWS-ECR-DEMO
          # filters r for when and how the jobs should run(ie feature branch, wch passes tests, integration tests)
          filters:
            branches:
              only:
                # we can use wild card that makes it run on feature branches or master branch /server\/.*/ use reg exp
                - master
      
