version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.2.1
  aws-ecs: circleci/aws-ecs@3.2.0
  python:  circleci/python@2.1.1

jobs:
  aws-ecr:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest
      - setup_remote_docker:
          version: 20.10.11
      - aws-ecr/build-and-push-image:
          public-registry: true
          dockerfile: Dockerfile
          repo: aws
          tag: latest,$CIRCLE_SHA1
    
      # - aws-ecs/deploy-service-update: # orb built-in job
      #     requires:
      #       - aws-ecr/build-and-push-image
      #     family: '${MY_APP_PREFIX}-service'
      #     cluster: '${MY_APP_PREFIX}-cluster'
      #     container-image-name-updates: 'container=${MY_APP_PREFIX}-service,tag=${CIRCLE_SHA1}'

workflows:
  build-and-push-to-ecr:
    jobs:
      - aws-ecr:
          context:
            - AWS-ECR-DEMO
          filters:
            branches:
              only:
                - master
      
