version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.3.0

jobs:
  aws-ecr:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest
      - setup_remote_docker:
          version: 20.10.11
      - aws-ecr/build-and-push-image:
          dockerfile: Dockerfile
          repo: aws
          tag: latest,$CIRCLE_SHA1

workflows:
  build-and-push-to-ecr:
    jobs:
      - aws-ecr:
          context:
            - AWS-ECR-DEMO
          filters:
            branches:
              only:
                - master